require("dotenv").config();

const mongoose = require("mongoose");

const { connect, Pokemon } = require("./models");
const populaBancoDeDados = async () => {
  connect();

  await Pokemon.create([
    {
      id: 243,
      nome: "raikou",
      altura: 19,
      peso: 1780,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/243.png",
      ataques: "pressure, inner-focus",
      estatisticas: {
        hp: 90,
        attack: 85,
        defense: 75,
        "special-attack": 115,
        "special-defense": 100,
        speed: 115,
      },
      jogos: [
        "gold",
        "silver",
        "crystal",
        "ruby",
        "sapphire",
        "emerald",
        "firered",
        "leafgreen",
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 27,
      nome: "sandshrew",
      altura: 6,
      peso: 120,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png",
      ataques: "sand-veil, sand-rush",
      estatisticas: {
        hp: 50,
        attack: 75,
        defense: 85,
        "special-attack": 20,
        "special-defense": 30,
        speed: 40,
      },
      jogos: [
        "red",
        "blue",
        "yellow",
        "gold",
        "silver",
        "crystal",
        "ruby",
        "sapphire",
        "emerald",
        "firered",
        "leafgreen",
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 279,
      nome: "pelipper",
      altura: 12,
      peso: 280,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/279.png",
      ataques: "keen-eye, drizzle, rain-dish",
      estatisticas: {
        hp: 60,
        attack: 50,
        defense: 100,
        "special-attack": 95,
        "special-defense": 70,
        speed: 65,
      },
      jogos: [
        "ruby",
        "sapphire",
        "emerald",
        "firered",
        "leafgreen",
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 420,
      nome: "cherubi",
      altura: 4,
      peso: 33,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/420.png",
      ataques: "chlorophyll",
      estatisticas: {
        hp: 45,
        attack: 35,
        defense: 45,
        "special-attack": 62,
        "special-defense": 53,
        speed: 35,
      },
      jogos: [
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 676,
      nome: "furfrou",
      altura: 12,
      peso: 280,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/676.png",
      ataques: "fur-coat",
      estatisticas: {
        hp: 75,
        attack: 80,
        defense: 60,
        "special-attack": 65,
        "special-defense": 90,
        speed: 102,
      },
    },
    {
      id: 212,
      nome: "scizor",
      altura: 18,
      peso: 1180,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/212.png",
      ataques: "swarm, technician, light-metal",
      estatisticas: {
        hp: 70,
        attack: 130,
        defense: 100,
        "special-attack": 55,
        "special-defense": 80,
        speed: 65,
      },
      jogos: [
        "gold",
        "silver",
        "crystal",
        "ruby",
        "sapphire",
        "emerald",
        "firered",
        "leafgreen",
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 471,
      nome: "glaceon",
      altura: 8,
      peso: 259,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/471.png",
      ataques: "snow-cloak, ice-body",
      estatisticas: {
        hp: 65,
        attack: 60,
        defense: 110,
        "special-attack": 130,
        "special-defense": 95,
        speed: 65,
      },
      jogos: [
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 427,
      nome: "buneary",
      altura: 4,
      peso: 55,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/427.png",
      ataques: "run-away, klutz, limber",
      estatisticas: {
        hp: 55,
        attack: 66,
        defense: 44,
        "special-attack": 44,
        "special-defense": 56,
        speed: 85,
      },
      jogos: [
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 405,
      nome: "luxray",
      altura: 14,
      peso: 420,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/405.png",
      ataques: "rivalry, intimidate, guts",
      estatisticas: {
        hp: 80,
        attack: 120,
        defense: 79,
        "special-attack": 95,
        "special-defense": 79,
        speed: 70,
      },
      jogos: [
        "diamond",
        "pearl",
        "platinum",
        "heartgold",
        "soulsilver",
        "black",
        "white",
        "black-2",
        "white-2",
      ],
    },
    {
      id: 762,
      nome: "steenee",
      altura: 7,
      peso: 82,
      imagem:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/762.png",
      ataques: "leaf-guard, oblivious, sweet-veil",
      estatisticas: {
        hp: 52,
        attack: 40,
        defense: 48,
        "special-attack": 40,
        "special-defense": 48,
        speed: 62,
      },
      jogos: [],
    },
  ]);
  await mongoose.disconnect();
};

populaBancoDeDados();
